name: tests.master

on:
  push:
    branches:
      - master

jobs:

  build-run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Src
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build
